### ISSUE TITLE
bug: lots of `{"timestamp":"2023-06-11T03:02:35.072995Z","level":"ERROR","fields":{"message":"ProjectRegistry::project_data: invalid response: 400 Bad Request"},"target":"bouncer","span":{"project_id":"squid-app","name":"get_allowed_domains"},"spans":[{"project_id":"squid-app","name":"get_allowed_domains"}]}` thrown

### ISSUE THREAD

**Issue by arein** [WalletConnect/bouncer#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lots of HTTP500 responses on verify

Possible root cause is `[{"timestamp":"2023-06-11T03:02:35.072995Z","level":"ERROR","fields":{"message":"ProjectRegistry::project_data: invalid response: 400 Bad Request"},"target":"bouncer","span":{"project_id":"squid-app","name":"get_allowed_domains"},"spans":[{"project_id":"squid-app","name":"get_allowed_domains"}]}](https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logs-insights:queryDetail=~(end~'2023-06-11T03*3a05*3a55.520Z~start~'2023-06-10T21*3a05*3a55.520Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20*40message*20*7c*0a*20filter*20*40message*20not*20like*20*2fINFO*7cWARN*2f*20*7c*0a*20sort*20*40timestamp*20desc*20*7c*0a*20limit*2020~isLiveTail~false~source~(~'arn*3aaws*3alogs*3aeu-central-1*3a898587786287*3alog-group*3aprod-verify_logs)))`

Not sure what the root cause is for that

### Expected Behavior

Not HTTP500s

### Steps To Reproduce

Only checked logs

### Environment

```markdown
- OS:
- rustc:
- cargo:
```

**Comment by xDarksome** [comment]
Going to be fixed by #25
